# Generated by Django 4.1 on 2022-09-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_delete_entregable_delete_familia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
    ]
