# Generated by Django 4.1 on 2022-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_blog_delete_curso_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.CharField(default='Hoy', max_length=40),
        ),
    ]
