# Generated by Django 4.1 on 2022-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_blog_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='blog',
            name='contenido',
            field=models.CharField(default=' ', max_length=900),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
