# Generated by Django 4.1 on 2022-10-01 18:35

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_remove_blog_imagen_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
