# Generated by Django 4.1 on 2022-10-02 06:56

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0008_remove_blog_imagen_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='mini_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
