# Generated by Django 4.1 on 2022-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_blog_contenido_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.CharField(default='Hoy', max_length=40),
        ),
    ]
