# Generated by Django 4.1 on 2022-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_alter_blog_author_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mini_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
