# Generated by Django 4.1 on 2022-10-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_blogcomment_blog_slug_delete_blogimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
    ]
