# Generated by Django 4.1 on 2022-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
