# Generated by Django 4.1 on 2022-10-02 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0013_remove_blog_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
