# Generated by Django 4.1 on 2022-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_alter_blog_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
