# Generated by Django 4.1 on 2022-10-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_alter_blog_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contenido',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitulo',
            new_name='mini_description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='fecha',
            new_name='post_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='numero',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
