# Generated by Django 4.1 on 2022-09-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='use',
            new_name='user',
        ),
    ]
